name: Build and Deploy
on:
  deployment:
    branches:
      - "gh-pages"
  deployment_status:
    branches:
      - "gh-pages"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Publish WebHook
        env:
          PAGES_PUBLIC_URL: https://blfunex.github.io/vx/
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          node ".github/workflows/discord-site.js"
